### ISSUE TITLE
little tweak I'd like to suggest

### ISSUE THREAD

**Issue by takemeoutofthisexistencialnightmare** [ZenKitty/RoR2ToggleSprintTweak#1]
so, I downloaded the mod, love being able to just spam sprint without it toggling off, but I noticed that it also makes it so that you can sprint to any direction, any chance you could fix that?
I know it's a buff, not a nerf, but I'd like to keep my game as close to vanilla as possible while enhancing QoL
thanks!
edit: honestly, no need, it's probably a lot more fun this way
edit2: after playing with it for a while, it really is so much more fun this way, thanks for the mod! (please keep it like this)

**Comment by ZenKitty** [comment]
Either way thanks for the heads up! This mod was thrown together really quick so maybe I'll consider adding a configuration option for that. I think it's a pretty easy fix/addition so I'll look into it.

**Comment by takemeoutofthisexistencialnightmare** [comment]
yeah, I just started playing the game and was really bothered by the sprint since it toggles on/off and there's no hold option, but your mod totally solves that
then I noticed how it allows you to run in all directions and was kinda split because it felt great having that feature but it felt kinda cheating (that's why I closed and reopened the thing multiple times, that and me having no idea on how to use github), but I got around to it eventually, it's not that big of a change but it feels so good to have it
anyway, thanks for the amazing mod!
